import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./Provider";
import Header from "./components/Header";

// Add display: 'swap' to prevent layout shift
const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="text-black">
        <Provider>
        {/* <Header /> */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
